SELECT COUNT(*) FROM cast_info ci WHERE ci_person_id=172968;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t_id=mi_movie_id AND t_kind_id<3 AND t_production_year=2008 AND mi_info_type_id>2;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t_id=ci_movie_id AND ci_person_id<3194645;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t_id=ci_movie_id AND t_id=mi_movie_id AND ci_person_id=1742124 AND ci_role_id>2 AND mi_info_type_id<7;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t_id=ci_movie_id AND t_id=mi_idx_movie_id AND t_kind_id=7 AND t_production_year>0 AND ci_role_id=2 AND mi_idx_info_type_id=101;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t_id=mc_movie_id AND t_production_year<2000 AND mc_company_id=160 AND mc_company_type_id=2;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t_id=mc_movie_id AND t_id=mi_idx_movie_id AND mc_company_id<77942 AND mc_company_type_id>1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk_keyword_id<71692;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t_id=ci_movie_id AND t_id=mi_idx_movie_id AND ci_person_id>681261 AND ci_role_id>1 AND mi_idx_info_type_id=99;
SELECT COUNT(*) FROM movie_companies mc WHERE mc_company_id<9749 AND mc_company_type_id>1;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t_id=mc_movie_id AND t_id=mk_movie_id AND mc_company_id=43268 AND mk_keyword_id<2560;
SELECT COUNT(*) FROM cast_info ci WHERE ci_person_id>1278953 AND ci_role_id<2;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t_id=mk_movie_id AND mk_keyword_id<1029;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t_id=mc_movie_id AND t_id=mi_movie_id AND t_kind_id<7 AND mc_company_id>83328 AND mi_info_type_id<8;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t_id=mc_movie_id AND t_id=mi_idx_movie_id AND t_kind_id=7 AND t_production_year=1994 AND mc_company_id>50785 AND mc_company_type_id>1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc_company_id<80833 AND mc_company_type_id=1;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t_id=ci_movie_id AND ci_person_id<2945474 AND ci_role_id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk_keyword_id>2237;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t_id=mc_movie_id AND t_kind_id>4 AND t_production_year<2004 AND mc_company_id<5363;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t_id=mc_movie_id AND t_id=mi_idx_movie_id AND t_kind_id=7 AND t_production_year=2013 AND mc_company_id<239 AND mc_company_type_id<2;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t_id=mk_movie_id AND mk_keyword_id=62398;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t_id=mc_movie_id AND mc_company_id<213849 AND mc_company_type_id>1;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t_id=ci_movie_id AND ci_person_id>284738;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t_id=mk_movie_id AND mk_keyword_id<80578;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t_id=mi_movie_id AND t_id=mi_idx_movie_id AND t_production_year>1978 AND mi_info_type_id=3;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t_id=mc_movie_id AND t_id=mi_movie_id AND t_kind_id<4 AND t_production_year=1966 AND mc_company_id<7563 AND mc_company_type_id=2 AND mi_info_type_id>6;
SELECT COUNT(*) FROM cast_info ci WHERE ci_person_id<1436321;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t_id=ci_movie_id AND ci_person_id=2610477 AND ci_role_id<3;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t_id=mc_movie_id AND mc_company_id=43276 AND mc_company_type_id>1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc_company_id>1127 AND mc_company_type_id=1;